### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by ScottGuymer** [carolynvs/Flurl.Signed#1]
Hi

Thanks for this great signed version.

However it doesnt seem to be up to date with them main Flurl repo.

That is on 0.10 and this is on 0.7

**Comment by carolynvs** [comment]
Thanks for the heads up. I'll fix the CI job which checks for new versions and publishes signed counterparts.

**Comment by carolynvs** [comment]
@ScottGuymer All fixed! https://www.nuget.org/packages/Flurl.Signed/2.0.0

**Comment by ScottGuymer** [comment]
Awesome thanks!!

**Comment by gitfool** [comment]
Hi @carolynvs. There's a new version of Flurl (and Flurl.Http). I'd love to have the signed versions; thanks! 😉

**Comment by carolynvs** [comment]
Unfortunately the build server where I was automatically publishing new signed packages from isn't mine anymore (old employer). I'm not sure when I'll have time to move it to a permanent home, most likely myget.

In the meantime, all the commands you need to sign it yourself during your own build are in this repo (along with the private key that I used).

I'll report back on this issue if/when I get a new build up.

**Comment by tmenier** [comment]
@carolynvs Sorry to hear that. I know there are many others who need signed packages and it's nice to have them automatically available on NuGet obviously. Do you want me to see if someone else would be willing to take this on or do you still plan on getting it back up sometime? Flurl.Http 2.0 is coming soon and it would be great to have it available by then. Thanks!

**Comment by carolynvs** [comment]
Honestly, I have too much on my plate right now. So if someone else would like to take my repo and get it up and running on MyGet, that would be amazingly helpful.

**Comment by tmenier** [comment]
@kroniak is this something you might able to look into? Since you are very familiar with MyGet and AppVeyor (and Flurl!) I thought you might be the right person to take this on. Assuming you have the time of course.

**Comment by kroniak** [comment]
@tmenier  I was come back to my city and I will look this

**Comment by tmenier** [comment]
@carolynvs @kroniak Any updates on your time availability to get this working again? 2.0 will be released by week's end and it'll be a real bummer if those who have come to depend on the signed packages can't upgrade.

**Comment by tmenier** [comment]
@ScottGuymer @gitfool If you still need signed packages please [volunteer](https://github.com/tmenier/Flurl/issues/39#issuecomment-334450189) to help get them up and running again. Thanks.

**Comment by gitfool** [comment]
I no longer use the signed packages. 😉
