### ISSUE TITLE
Please update or delist packages

### ISSUE THREAD

**Issue by tmenier** [carolynvs/Flurl.Signed#2]
I continue to get questions about the signed packages (understandably) and why they are so out of date. If you are not going to update it, then to avoid confusion please delist Flurl.Signed and Flurl.Http.Signed from NuGet. Thank you.

**Comment by carolynvs** [comment]
Sorry about that! I have unlisted the packages from nuget.

**Comment by tmenier** [comment]
No worries, thanks.
